run:
  timeout: 5m
linters:
  fast: false
  disable:
    - gomnd
    - funlen    
    - nlreturn
    - stylecheck
    - revive
    - wrapcheck
  enable:
    - asciicheck
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - exportloopref
    - staticcheck
    - testpackage
    - unconvert
    - unused
    - whitespace
    - maligned
    - ifshort
